/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sciborgs1155.dashboard;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.Background;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import org.sciborgs1155.dashboard.Network.Server;

/** Main class for starting the app. */
public class App extends Application {
  /** Contains every other {@link Pane} in the app. */
  public static final BorderPane mainPane = new BorderPane();

  /** A scene composed of the {@link #mainPane}. */
  public static final Scene mainScene = new Scene(mainPane, 1280, 720);

  /** Starts the window(given as an {@link Stage}) */
  @Override
  public void start(Stage stage) {
    /** Removes the default title bar */
    stage.initStyle(StageStyle.UNDECORATED);
    stage.initStyle(StageStyle.TRANSPARENT);

    mainScene.setFill(Color.TRANSPARENT);
    stage.setWidth(mainScene.getWidth());
    stage.setHeight(mainScene.getHeight());
    stage.setScene(mainScene);

    stage.setResizable(true);

    stage.setTitle("SciBoard 2025");
    stage
        .getIcons()
        .add(
            new Image(
                ClassLoader.getSystemResourceAsStream("SciborgIcons/sciborgDisconnected.png")));

    mainPane.setBackground(Background.fill(Color.BLACK));

    stage.setMaximized(true);
    stage.show();

    Network.load();
    Network.connect(Server.SIMULATION);
    Network.startNetworkThread(stage);
  }

  /**
   * Runs the program.
   *
   * @param args : Arguments to run the program with.
   */
  public static void main(String[] args) {
    launch();
  }
}
