/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sciborgs1155.dashboard;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

/** Main class for starting the app. */
public class App extends Application {
    /** Starts the window(given as a {@link Stage}) */
    @Override
    public void start(Stage stage) {
        Button button = new Button("Yippee!");

        Network.start();
        button.setOnAction((ActionEvent event) -> {
            System.out.println("YIPPEE!");
            event.consume();
        });
        
        Scene scene = new Scene(new StackPane(button), 640, 480);

        stage.setScene(scene);

        stage.setTitle("SciBoard");
        stage.getIcons().add(new Image(ClassLoader.getSystemResourceAsStream("Icon.png")));
        stage.show();
    }

    /**
     * Runs the program.
     * 
     * @param args : Arguments to run the program with.
     */
    public static void main(String[] args) {
        launch();
    }

}